language: python
python:
  - "3.4"
  - "3.5"
services:
  - postgresql
install:
  - pip install -r web/requirements.txt
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - cd web
script:
  - ./manage.py lint
  - ./manage.py test
notifications:
  - email: false
