"""Added is_active flag for users

Revision ID: 6b54c647496e
Revises: 196516f3284c
Create Date: 2016-04-30 17:50:01.631255

"""

# revision identifiers, used by Alembic.
revision = '6b54c647496e'
down_revision = '196516f3284c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('workdays_base_schedule_id_fkey', 'workdays', type_='foreignkey')
    op.create_foreign_key(None, 'workdays', 'base_schedules', ['base_schedule_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workdays', type_='foreignkey')
    op.create_foreign_key('workdays_base_schedule_id_fkey', 'workdays', 'roles', ['base_schedule_id'], ['id'])
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###
