"""Added work_hours for Users.

Revision ID: 942327552051
Revises: 6b54c647496e
Create Date: 2016-05-11 09:28:37.858612

"""

# revision identifiers, used by Alembic.
revision = '942327552051'
down_revision = '6b54c647496e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('work_hours', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_hours')
    ### end Alembic commands ###
